services:
  - type: web
    name: erp-architecte
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///%kernel.project_dir%/var/data.db"
      - key: MAILER_DSN
        value: "null://null"
